### ISSUE TITLE
关于咨询信安赛的问题

### ISSUE THREAD

**Issue by chentao1998** [zhengjilai/Raft-based-Distributed-Lock#1]
尊敬的学长：
    您好，我是上交信安学院18级的一名学生，打算参加信安大赛。在拜读您的作品时，遇到很多操作性上的问题。请问学长能否留个QQ，学弟以咨询您相关问题。可有偿。
          您的学弟

**Comment by zhengjilai** [comment]
> 尊敬的学长：
> 您好，我是上交信安学院18级的一名学生，打算参加信安大赛。在拜读您的作品时，遇到很多操作性上的问题。请问学长能否留个QQ，学弟以咨询您相关问题。可有偿。
> 您的学弟

总体而言那是一个失败的作品，并且最终也没有拿到什么大荣誉，没有很大的参考价值。
不过如果确实有疑问，可以发送你的qq到我的邮箱，zhengjilai@sjtu.edu.cn，我们单独联系。
